### ISSUE TITLE
Flakey Test

### ISSUE THREAD

**Issue by sarahzinger** [grafana/opensearch-datasource#246]
These 2 drone builds were run on the same code, one failed and one passed: 
https://drone.grafana.net/grafana/opensearch-datasource/465
https://drone.grafana.net/grafana/opensearch-datasource/466

```
Summary of all failing tests
FAIL src/components/QueryEditor/MetricAggregationsEditor/SettingsEditor/index.test.tsx (38.745 s)
  ● Settings Editor › Raw Data › Should correctly render the settings editor and trigger correct state changes

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       9 | describe('Settings Editor', () => {
      10 |   describe('Raw Data', () => {
    > 11 |     it('Should correctly render the settings editor and trigger correct state changes', async () => {
         |     ^
      12 |       const metricId = '1';
      13 |       const initialSize = '500';
      14 |       const initialOrder = 'desc';

      at src/components/QueryEditor/MetricAggregationsEditor/SettingsEditor/index.test.tsx:11:5
      at src/components/QueryEditor/MetricAggregationsEditor/SettingsEditor/index.test.tsx:10:3
      at Object.<anonymous> (src/components/QueryEditor/MetricAggregationsEditor/SettingsEditor/index.test.tsx:9:1)
```

**Comment by katebrenner** [comment]
closing as not planned
