### ISSUE TITLE
Grafana datasource issue

### ISSUE THREAD

**Issue by znqerz** [grafana/opensearch-datasource#27]
Grafana version: 8.4.7
DS version:1.1.2
Opensearch version: 1.3.1

1st, there is no same version option in "OpenSearch details" version sections.
2ed, try to connect use http with basic auth to connect to opensearch, but returned "OpenSearch error: Bad Gateway"

Check with opensearch log here is the details:

[2022-04-15T10:15:42,520][WARN ][o.o.h.AbstractHttpServerTransport] [opensearch-cluster-master-0] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=0.0.0.0/0.0.0.0:9200, remoteAddress=null}
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f78706572662d2a2f5f6d617070696e6720485454502f312e310d0a486f73743a206f70656e7365617263682d636c75737465722d6d61737465722e6f70656e7365617263682e7376632e636c75737465722e6c6f63616c3a393230300d0a557365722d4167656e743a2047726166616e612f382e342e360d0a4163636570743a206170706c69636174696f6e2f6a736f6e2c20746578742f706c61696e2c202a2f2a0d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174652c2062720d0a4163636570742d4c616e67756167653a20656e2d55532c656e3b713d302e392c7a682d434e3b713d302e382c7a683b713d302e370d0a417574686f72697a6174696f6e3a204261736963206233426c626e4e6c59584a6a614470455156643661573159524731325954593d0d0a446e743a20310d0a5365632d43682d55613a2022204e6f7420413b4272616e64223b763d223939222c20224368726f6d69756d223b763d22313030222c2022476f6f676c65204368726f6d65223b763d22313030220d0a5365632d43682d55612d4d6f62696c653a203f300d0a5365632d43682d55612d506c6174666f726d3a20226d61634f53220d0a5365632d46657463682d446573743a20656d7074790d0a5365632d46657463682d4d6f64653a20636f72730d0a5365632d46657463682d536974653a2073616d652d6f726967696e0d0a582d466f727761726465642d466f723a203132372e302e302e312c203132372e302e302e310d0a582d47726166616e612d4e6f63616368653a20747275650d0a582d47726166616e612d4f72672d49643a20310d0a0d0a
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.73.Final.jar:4.1.73.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f78706572662d2a2f5f6d617070696e6720485454502f312e310d0a486f73743a206f70656e7365617263682d636c75737465722d6d61737465722e6f70656e7365617263682e7376632e636c75737465722e6c6f63616c3a393230300d0a557365722d4167656e743a2047726166616e612f382e342e360d0a4163636570743a206170706c69636174696f6e2f6a736f6e2c20746578742f706c61696e2c202a2f2a0d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174652c2062720d0a4163636570742d4c616e67756167653a20656e2d55532c656e3b713d302e392c7a682d434e3b713d302e382c7a683b713d302e370d0a417574686f72697a6174696f6e3a204261736963206233426c626e4e6c59584a6a614470455156643661573159524731325954593d0d0a446e743a20310d0a5365632d43682d55613a2022204e6f7420413b4272616e64223b763d223939222c20224368726f6d69756d223b763d22313030222c2022476f6f676c65204368726f6d65223b763d22313030220d0a5365632d43682d55612d4d6f62696c653a203f300d0a5365632d43682d55612d506c6174666f726d3a20226d61634f53220d0a5365632d46657463682d446573743a20656d7074790d0a5365632d46657463682d4d6f64653a20636f72730d0a5365632d46657463682d536974653a2073616d652d6f726967696e0d0a582d466f727761726465642d466f723a203132372e302e302e312c203132372e302e302e310d0a582d47726166616e612d4e6f63616368653a20747275650d0a582d47726166616e612d4f72672d49643a20310d0a0d0a
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1213) ~[netty-handler-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283) ~[netty-handler-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.73.Final.jar:4.1.73.Final]
	... 16 more

**Comment by znqerz** [comment]
For the error logs:
I found the error is for the datasource URL mission https prefix, so resolved after change URL.

But for the plugin issue, still can not use command:
grafana-cli plugins install grafana-opensearch-datasource
to install on the latest version of grafana.

**Comment by svennergr** [comment]
Hi @znqerz,
if I understood correctly this issue seems to be resolved. If anything remains open, please open a new issue.
Thanks!
