### ISSUE TITLE
TypeError: (0 , un.isAction) is not a function

### ISSUE THREAD

**Issue by marais-vzc** [grafana/opensearch-datasource#488]
**What happened**: TypeError: (0 , un.isAction) is not a function

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Add a panel, select opensearch datasource, see error below.

**Anything else we need to know?**:

![Image](https://github.com/user-attachments/assets/3175c160-ec43-449a-b941-ed6c9694c9eb)

```
TypeError: (0 , un.isAction) is not a function

    at Wn (https://grafana.dns/public/plugins/grafana-opensearch-datasource/module.js?_cache=2.20.0:26:18835)
    at eval (https://grafana.dns/public/plugins/grafana-opensearch-datasource/module.js?_cache=2.20.0:89:868)
    at o (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:1:172)
    at r (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:194:122084)
    at g (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:194:122593)
    at div
    at div
    at div
    at Ts (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:313:25179)
    at Sd (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:245:19376)
    at Mc (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:313:29655)
    at _f (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:313:29785)
    at p (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:422:68)
    at div
    at K (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:5381:820)
    at div
    at Ef (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:313:30071)
    at Sd (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:245:19376)
    at O (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:245:17081)
    at Fh (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:313:12800)
    at pt (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:255:961)
    at Is (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:313:14558)
    at g (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:5382:6035)
    at div
    at div
    at div
    at div
    at div
    at ne (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:320:4620)
    at u (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:194:29826)
    at J (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:5387:56)
    at Ln (https://grafana.dns/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:113:318)
    at div
    at s (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:286:58288)
    at div
    at https://grafana.dns/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:113:1766
    at div
    at div
    at o (https://grafana.dns/public/build/660.838743295c2108f3492d.js:1:2299)
    at div
    at o (https://grafana.dns/public/build/660.838743295c2108f3492d.js:1:4287)
    at N (https://grafana.dns/public/build/660.838743295c2108f3492d.js:1:9622)
    at div
    at o (https://grafana.dns/public/build/660.838743295c2108f3492d.js:1:2299)
    at div
    at o (https://grafana.dns/public/build/660.838743295c2108f3492d.js:1:4287)
    at N (https://grafana.dns/public/build/660.838743295c2108f3492d.js:1:9622)
    at div
    at div
    at div
    at U (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:370:21173)
    at Bn (https://grafana.dns/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:130:526)
    at lt (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:433:32639)
    at WithTheme(Connect(Bn))
    at yt (https://grafana.dns/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:205:472)
    at DashboardPage
    at lt (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:433:32639)
    at ms (https://grafana.dns/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:205:6334)
    at Suspense
    at r (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:194:122084)
    at Di (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:315:9679)
    at U (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:465:29190)
    at gi (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:456:4455)
    at si (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:456:12005)
    at mt (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:465:17389)
    at U (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:465:31358)
    at div
    at div
    at main
    at div
    at Ua (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:315:2409)
    at gi (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:456:4455)
    at si (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:456:12005)
    at hr (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:456:11341)
    at Yn (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:465:17688)
    at U (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:465:25428)
    at div
    at o (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:214:13884)
    at d (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:136:9042)
    at h (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:794:96447)
    at d (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:599:21174)
    at r (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:194:122084)
    at g (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:194:122593)
    at ot (https://grafana.dns/public/build/8838.45d6a14f4747f4596bfb.js:437:529)
    at Jr (https://grafana.dns/public/build/6279.fbe1f77e9d43e1be04e3.js:326:127)

Add query

Expression 

```

**Environment**:
- Grafana version: 9.4.5
- OpenSearch version: 1.3
- Plugin version: 2.21.0

**Comment by marais-vzc** [comment]
We upgraded to Grafana v11.3.0 today and don't see this issue anymore. I would say we can close this.

**Comment by idastambuk** [comment]
Hi @marais-vzc thanks for letting us know, closing this!

**Comment by faxm0dem** [comment]
I am having the same issue in  v10.4.14.
Data source is Opensearch (2.11.1).

We can't upgrade to 11 yet unfortunately, so could someone look into this please ?
